import {
  Mail,
  Home,
  Truck,
  Activity,
  Book,
  UserX,
  Users,
  MessageSquare,
  UserCheck,
  UserMinus,
  HelpCircle,
  CreditCard,
  ShieldOff,
  FileText,
  Sliders,
} from "react-feather";

export default [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: <Activity size={20} />,
    navLink: "/dashbaord/default",
  },
  {
    id: "cartype",
    title: "Car Type",
    icon: <Truck size={20} />,
    navLink: "/cartype",
  },
  // {
  //   id: "carcolors",
  //   title: "Car Colors",
  //   icon: <Sliders size={20} />,
  //   navLink: "/car-colors",
  // },
  {
    id: "ridefair",
    title: "Driver Fare",
    icon: <CreditCard size={20} />,
    navLink: "/driver-fair",
  },
  {
    id: "passenger_fair",
    title: "Passenger Fare",
    icon: <CreditCard size={20} />,
    navLink: "/passenger-fair",
  },
  {
    id: "users",
    title: "Users",
    icon: <Users size={20} />,
    navLink: "/users",
  },
  {
    id: "complaints",
    title: "Complaints",
    icon: <MessageSquare size={20} />,
    navLink: "/complaints",
  },
  {
    id: "noninsuranceusers",
    title: "Insurance",
    icon: <ShieldOff size={20} />,
    navLink: "/noninsuranceusers",
  },
  {
    id: "deleteduseraccounts",
    title: "Deleted Users",
    icon: <UserMinus size={20} />,
    navLink: "/deleteduseraccounts",
  },
  {
    id: "Wallet",
    title: "Wallet",
    icon: <CreditCard size={20} />,
    navLink: "/wallet",
  },
  // {
  //   id: "NonVerifiedUsers",
  //   title: "Non-Verified Users",
  //   icon: <UserX size={20} />,
  //   navLink: "/non-verify-users",
  // },
  {
    id: "VerificationRequests",
    title: "Verify Users",
    icon: <FileText size={20} />,
    navLink: "/verification-requests",
  },
];
